################################################################################
# Copyrights © 2021-2025 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: Provide support for Fiserv internal tenants to get resources and guides for configuring their product and documentation on Developer Studio.
featuredFeatures:
  - title: Onboarding
    description: Easy and straightforward process for requesting to be onboarded to Developer Studio with your own Github repository and helpful Teams channel for communication.
    relatedDocs:
      - relatedDoc: 
        title: Onboarding
        description: Onboarding document with step-by-step process
        link: docs/README.md
  - title: Configuring your product
    description: Provide guidance on the various configuration files and Github specific information we need from you to properly display your product on Developer Studio.
    relatedDocs:
      - relatedDoc: 
        title: Basic configurations
        description: Configuration files and usage
        link: docs/getting-started/configure-tenant.md
  - title: Markdown documentation
    description: Provide basic guidance for how to format your markdown documentation to display on Developer Studio with links, images, and downloadable files.
    relatedDocs:
      - relatedDoc: 
        title: markdown-syntax
        description: Markdown syntax guide
        link: docs/resources/markdown-syntax.md
  - title: API explorer
    description: Provide basic guidance for configuring your product with OpenAPI specifications to work with Developer Studio API explorer for displaying sample schema and example payloads.
    relatedDocs:
      - relatedDoc: 
        title: API Explorer
        description: API explorer and spec guide
        link: docs/getting-started/api-explorer.md
